apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-serverless-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/openshift-serverless-operator.openshift-operators: ''
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  labels:
    gitops.tier.group: serverless
spec: {}